version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    groups:
      tailwind:
        patterns:
          - tailwindcss
          - "@tailwindcss/*"
      vite:
        patterns:
          - vite
          - vitest
    pull-request-branch-name:
      separator: "-"
